method: PJDOT
dataset:
  name: Office31
  source_domain: webcam
  target_domain: dslr
  n_share: 31 # number of classes to be shared
  n_source_private: 0 # number of classes in source private domain
  n_total: 31 # number of classes in total
dataloader:
  class_balance: true
  num_workers: 8
  batch_size: 72
# train setting
print_interval: 100
test_interval: 500
max_step: 10000
# training parameters
lr: 0.00002
weight_decay: 0.0005
# weight between loss
param_b: 0.4
alpha: 0.001
lambda_t: 0.0001
# pre-train setting
no_pre_train: False # whether to use the pre-train model (on source)
pre_train_lr: 0.0001
pre_train_epochs: 10
pre_train_load_folder: ./pre_train_model